server:
  port: 8085
spring:
  redis:
    host: 192.168.211.138
  rabbitmq:
    host: 192.168.211.138
    username: nc
    password: nc
    virtual-host: /nc
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/nc?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

mybatis:
  type-aliases-package: com.nc.user.pojo