server:
  port: 10010
spring:
  application:
    name: nc-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:

  prefix: /api # 路由路径前缀
  routes:
    item-service: /item/** # 商品微服务的映射路径
    search-service: /search/** # 搜索微服务
    user-service: /user/** # 用户微服务
    auth-service: /auth/** # 授权中心微服务
    cart-service: /cart/** # 购物车微服务
  ignored-services:
    upload-service
  add-host-header: true
  sensitive-headers:
nc:
  jwt:
    pubKeyPath:  C:\\temp\\rsa\\rsa.pub # 公钥地址
    cookieName: NC_TOKEN # cookie的名称
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item